import { test, expect, activate, expectNoOverflow } from './fixtures.js';

test('liens: catalogue réel, cartes éditoriales et navigation par catégorie', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('.epic-card').first()).toBeVisible();
  await activate(page.locator('#tab-bookmarks'));
  const catalogue = await page.evaluate(async () => (await fetch('./data/bookmarks.json')).json());
  const categories = catalogue.categories.filter(category => category.bookmarks.length);
  const total = categories.reduce((sum, category) => sum + category.bookmarks.length, 0);
  await expect(page.locator('.bookmark-item')).toHaveCount(total);
  await expect(page.locator('#catalogue-status')).toHaveText(`${total} liens`);
  const cursor = page.locator('.bookmark-item a[href="https://cursor.com"]');
  await expect(cursor).toContainText('Éditeur de code');
  await expect(cursor.locator('.bookmark-description')).toBeVisible();
  await expect(cursor.locator('.bookmark-domain')).toHaveText('cursor.com');
  await expect(cursor).toContainText('Nouvelle fenêtre');
  await expect(cursor).toHaveAttribute('target', '_blank');
  await expect(cursor).toHaveAttribute('rel', /noopener/);
  await expect(page.locator('.bookmark-item img, .bookmark-icon, .bookmark-category-icon')).toHaveCount(0);
  const categoryOptions = page.locator('.bookmark-navigation-disclosure');
  await expect(categoryOptions).not.toHaveAttribute('open', '');
  await activate(categoryOptions.locator('summary'));
  const navigation = page.getByRole('navigation', { name: 'Catégories de liens' });
  await expect(navigation.getByRole('link')).toHaveCount(categories.length);
  const category = categories.find(item => item.id === 'resources');
  await activate(navigation.getByRole('link', { name: category.label, exact: true }));
  const heading = page.locator('#bookmark-category-resources-title');
  await expect(heading).toBeFocused();
  await expect(heading).toBeInViewport();
  await expect(categoryOptions).not.toHaveAttribute('open', '');
  await expect(page).toHaveURL(/#bookmark-category-resources-title$/);
  await expectNoOverflow(page);
});

test('liens: recherche accent-insensible, filtres secondaires et remise à zéro au clavier', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('.epic-card').first()).toBeVisible();
  await activate(page.locator('#tab-bookmarks'));
  await expect(page.locator('.bookmark-item').first()).toBeInViewport({ ratio: 0.5 });
  const total = await page.locator('.bookmark-item').count();
  const options = page.locator('#discovery-options');
  await expect(options).not.toHaveAttribute('open', '');
  await expect(page.locator('#bookmark-filters')).toBeHidden();
  await page.locator('#search').fill('CODE EDITEUR');
  await expect(page.locator('.bookmark-item a[href="https://cursor.com"]')).toBeVisible();
  await expect(page.locator('#search')).toBeFocused();
  await page.locator('#search').fill('');
  await activate(options.locator('summary'), 'Space');
  const filter = page.locator('#bookmark-filters [data-tag="ide"]');
  await activate(filter);
  await expect(filter).toBeFocused();
  await expect(filter).toHaveAttribute('aria-pressed', 'true');
  const tagCount = Number((await filter.textContent()).match(/\((\d+)\)/)[1]);
  await expect(page.locator('.bookmark-item')).toHaveCount(tagCount);
  await page.locator('#search').fill('cursor.com');
  await expect(page.locator('.bookmark-item')).toHaveCount(1);
  await activate(options.locator('summary'));
  await expect(options.locator('summary')).toContainText('ide');
  await page.locator('#search').fill('aucun-lien-impossible');
  await expect(page.locator('#empty-bookmarks')).toContainText('ne correspond');
  await expect(page.locator('#empty-bookmarks')).toBeVisible();
  await expect(page.locator('#catalogue-status')).toHaveText('0 liens');
  await activate(page.locator('#btn-reset-discovery'));
  await expect(page.locator('#search')).toHaveValue('');
  await expect(page.locator('#search')).toBeFocused();
  await expect(page.locator('.bookmark-item')).toHaveCount(total);
  await expect(page.locator('#btn-reset-discovery')).toBeHidden();
  await expect(page.locator('#empty-bookmarks')).toBeHidden();
});

test('liens: lecture mobile sans débordement ni preview et parcours clavier natif', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.locator('.epic-card').first()).toBeVisible();
  await activate(page.locator('#tab-bookmarks'));
  await expect(page.locator('.bookmark-item').first()).toBeInViewport({ ratio: 0.5 });
  await page.locator('#search').fill('cursor.com');
  await expect(page.locator('.bookmark-item')).toHaveCount(1);
  const card = page.locator('.bookmark-item a[href="https://cursor.com"]');
  await expect(card).toBeVisible();
  await card.focus();
  await expect(card).toBeFocused();
  await expect(card.locator('.bookmark-description')).toBeVisible();
  await expect(card).toContainText('Nouvelle fenêtre');
  await expect(page.locator('.bookmark-preview.visible')).toHaveCount(0);
  await expectNoOverflow(page);
  await page.keyboard.press('Shift+Tab');
  await expect(page.getByRole('heading', { name: /Outils de Coding IA/ })).not.toBeFocused();
  await expect(page.locator('.bookmark-navigation-disclosure summary')).toBeFocused();
});
